"""
5_executive_dashboard.py
------------------------
Streamlit page: Executive Dashboard
"""

import streamlit as st
import sys
import pandas as pd
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from src.data_generation.generate_data import generate_all_data
from src.forecasting.time_series import run_forecasting
from src.budget.variance_analysis import run_variance_analysis
from src.reporting.executive_dashboard import run_dashboard

st.set_page_config(page_title="Executive Dashboard", page_icon="🗂️", layout="wide")
st.title("🗂️ Executive Dashboard")
st.caption("One page · Four panels · All four business questions answered")
st.markdown("---")

# ---------------------------------------------------------------------------
# LOAD DATA
# ---------------------------------------------------------------------------

@st.cache_data(show_spinner="Loading data...")
def load_data():
    return generate_all_data(save=False)

@st.cache_data(show_spinner="Running models...")
def load_models(contacts_df, costs_df):
    forecast  = run_forecasting(contacts_df=contacts_df)
    variance  = run_variance_analysis(costs_df=costs_df)
    return forecast, variance

datasets                    = load_data()
forecast_results, variance_results = load_models(
    datasets['contacts'], datasets['costs']
)

# ---------------------------------------------------------------------------
# DASHBOARD IMAGE (pre-generated)
# ---------------------------------------------------------------------------

st.subheader("Executive Dashboard")
dashboard_path = Path("outputs/executive_dashboard.png")

if dashboard_path.exists():
    st.image(str(dashboard_path), use_container_width=True)
    st.caption("Generated by `src/reporting/executive_dashboard.py` | 180 DPI")
else:
    st.warning("Dashboard image not found. Run `python main.py` first.")
    if st.button("Generate Dashboard Now"):
        with st.spinner("Building dashboard..."):
            run_dashboard(
                contacts_df     = datasets['contacts'],
                costs_df        = datasets['costs'],
                satisfaction_df = datasets['satisfaction'],
                forecast_df     = forecast_results['summary'],
                variance_df     = variance_results['brand_summary'],
            )
        st.success("Dashboard generated. Refresh the page.")

st.markdown("---")

# ---------------------------------------------------------------------------
# EXECUTIVE NARRATIVE
# ---------------------------------------------------------------------------

st.subheader("Executive Summary Narrative")
narrative_path = Path("outputs/reports/executive_summary.txt")

if narrative_path.exists():
    narrative = narrative_path.read_text()
    st.code(narrative, language=None)
    st.download_button(
        label="Download Executive Summary",
        data=narrative,
        file_name="executive_summary.txt",
        mime="text/plain"
    )
else:
    st.info("Narrative will appear here after running the pipeline.")

st.markdown("---")

# ---------------------------------------------------------------------------
# KPI SCORECARD (live computed)
# ---------------------------------------------------------------------------

st.subheader("KPI Scorecard — Live")
st.caption("Computed directly from the raw data on this session.")

contacts_df     = datasets['contacts']
costs_df        = datasets['costs']
satisfaction_df = datasets['satisfaction']

total_contacts  = contacts_df['contact_volume'].sum()
total_actual    = costs_df['actual_cost'].sum()
total_budget    = costs_df['budget_cost'].sum()
var_pct         = (total_actual - total_budget) / total_budget * 100
avg_csat        = satisfaction_df['csat_score'].mean()
avg_fcr         = satisfaction_df['first_contact_resolution'].mean() * 100
cost_per_contact = total_actual / total_contacts

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Total Contacts",    f"{total_contacts:,.0f}")
col2.metric("Total Actual Cost", f"R{total_actual/1e6:.2f}M")
col3.metric("Budget Variance",   f"+{var_pct:.1f}%",  "+9.6%")
col4.metric("Avg CSAT",          f"{avg_csat:.2f}",   "/ 10  (target 7.5)")
col5.metric("Cost per Contact",  f"R{cost_per_contact:.2f}")

st.markdown("---")

# ---------------------------------------------------------------------------
# DOWNLOAD DASHBOARD
# ---------------------------------------------------------------------------

if dashboard_path.exists():
    with open(dashboard_path, 'rb') as f:
        st.download_button(
            label="📥 Download Dashboard PNG",
            data=f,
            file_name="executive_dashboard.png",
            mime="image/png"
        )
